package io.github.dornol.idkit.uuidv7

import java.time.Instant

/** Decoded fields of a UUID v7 generated by idkit. */
data class UuidV7Components(
    val timestamp: Instant,
    val counter: Long,
    /** The 62-bit `rand_b` field, represented as a non-negative Long. */
    val randomBits: Long,
)
